import React,{useEffect,useState} from 'react';
import {createLabClient} from './client';
export function modelProvider(id:string){const s=id.toLowerCase();if(/gpt|codex|openai|(?:^|\/)o[134](?:-|$)/.test(s))return 'OpenAI';if(/claude|anthropic/.test(s))return 'Anthropic';if(/deepseek/.test(s))return 'DeepSeek';if(/gemini|gemma|google/.test(s))return 'Google';if(/qwen|qwq|qvq|wan[-/]/.test(s))return '阿里云 · Qwen';if(/kimi|moonshot/.test(s))return 'Moonshot · Kimi';if(/glm|zhipu/.test(s))return '智谱 · GLM';if(/minimax/.test(s))return 'MiniMax';if(/doubao|seed|bytedance/.test(s))return '字节跳动';if(/llama|meta/.test(s))return 'Meta';if(/mistral|mixtral/.test(s))return 'Mistral';if(/grok|xai/.test(s))return 'xAI';if(/^(pa|hermes)\//.test(s))return '服务商别名 · 厂商未标明';if(/^inception\//.test(s))return 'Inception';return '其他模型';}
export function ModelPicker({client,configured,models,value,onChange}:{client:ReturnType<typeof createLabClient>;configured:boolean;models:string[];value:string[];onChange:(ids:string[])=>void}){
 const [catalog,setCatalog]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[provider,setProvider]=useState('');
 async function load(){setLoading(true);setError('');try{setCatalog((await client.modelCatalog()).models);}catch(e){setError(e instanceof Error?e.message:'模型目录加载失败');}finally{setLoading(false);}}
 useEffect(()=>{if(configured)void load();},[client,configured]);
 const all=[...new Set([...catalog,...models])].filter(Boolean).sort();const providers=[...new Set(all.map(modelProvider))].sort();const filtered=all.filter(id=>(!provider||modelProvider(id)===provider)&&id.toLowerCase().includes(query.toLowerCase()));
 return <div className="lab-model-picker"><div className="lab-run-heading"><input type="search" aria-label="搜索模型" placeholder="搜索模型名称" value={query} onChange={e=>setQuery(e.target.value)}/><button type="button" disabled={loading||!configured} onClick={()=>void load()}>{loading?'加载目录中…':'刷新模型目录'}</button></div>
 <p className="lab-muted">服务目录 {catalog.length} 个 · 已选 {value.length} / 5 个。目录来自当前配置的 API 服务，实际调用权限取决于账号。</p>
 {error&&<p role="alert" className="lab-alert lab-alert-error">{error}。当前仅显示本地已配置模型，可点击刷新重试。</p>}
 <div className="lab-provider-tabs" aria-label="模型厂商">{['',...providers].map(p=><button type="button" key={p} aria-pressed={provider===p} onClick={()=>setProvider(p)}>{p||'全部厂商'}{p&&`（${all.filter(id=>modelProvider(id)===p).length}）`}</button>)}</div>
 <div className="lab-model-catalog">{providers.filter(p=>!provider||p===provider).map(p=>{const items=filtered.filter(id=>modelProvider(id)===p);return items.length?<section key={p}><h3>{p}</h3><div className="lab-run-models">{items.map(id=><label className="lab-check" key={id}><input type="checkbox" checked={value.includes(id)} disabled={!value.includes(id)&&value.length>=5} onChange={e=>onChange(e.target.checked?[...value,id]:value.filter(v=>v!==id))}/><span>{id}{!catalog.includes(id)&&<small>本地配置 · 未在目录确认</small>}</span></label>)}</div></section>:null;})}{!filtered.length&&!loading&&<p>没有匹配模型，请调整搜索或刷新目录。</p>}</div>
 {value.length>0&&<p className="lab-muted">已选：{value.join('、')} <button type="button" onClick={()=>onChange([])}>清空模型</button></p>}
 <details><summary>Codex / Claude Code 接入说明</summary><p>这里选择 API 模型。Codex 和 Claude Code 工具需要独立的执行适配；当前未接入工具运行。目录中的 GPT、Codex、Claude 模型按实际模型 ID 调用。</p></details></div>;
}
