import {Pagination,pageSlice} from './Pagination';
import {ModelPicker} from './ModelPicker';
import React,{useRef,useState} from 'react';
import type {LabBootstrap,LabRun,LabRunSelection} from './types';
import {createLabClient} from './client';
import {FilterSelect} from './FilterSelect';
import {ComparisonReport,scoreRun} from './comparison';
import {Empty,RunDetails} from './views';
import {downloadJson,isActiveRun,runLabels,uid} from './model';

export function eligibleCases(b:LabBootstrap,teamId:string,skillId:string,actorId:string){
 const team=b.state.teams.find(t=>t.id===teamId&&!t.archived);
 if(!team?.members.some(m=>m.id===actorId))return [];
 return b.state.cases.filter(c=>c.teamId===teamId&&!c.archived&&c.enabled&&c.steps.every(s=>s.skillId===skillId)&&c.steps.every(s=>(s.skillId==='agentdoor-task-planner'&&c.creationContext==='fresh')||!s.taskId||team.tasks.some(t=>t.id===s.taskId&&(t.visibility==='team'||t.ownerId===actorId||t.participantIds.includes(actorId)))));
}
export function groupRuns(runs:LabRun[]){const groups=new Map<string,LabRun[]>();for(const run of runs){const key=run.batchId||run.id;groups.set(key,[...(groups.get(key)??[]),run]);}return [...groups.entries()].sort((a,b)=>b[1][0].createdAt.localeCompare(a[1][0].createdAt));}

export function RunCenter({bootstrap,client,onRefresh,seed}:{bootstrap:LabBootstrap;client:ReturnType<typeof createLabClient>;onRefresh:()=>Promise<void>;seed?:{id:string;caseIds:string[]}}){
 const [creating,setCreating]=useState(!!seed);const [batch,setBatch]=useState<string|null>(null);const [detail,setDetail]=useState<string|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const groups=groupRuns(bootstrap.state.runs);const selected=groups.find(([id])=>id===batch)?.[1]??[];const run=selected.find(r=>r.id===detail);
 async function action(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await onRefresh();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}}
 if(creating)return <RunComposer client={client} bootstrap={bootstrap} initialIds={seed?.caseIds??[]} onCancel={()=>setCreating(false)} onStart={async(ids,selection,requestId)=>{const result=await client.run(ids,requestId,selection);setBatch(result[0].batchId);setDetail(null);setCreating(false);await onRefresh();}}/>;
 return <section className="lab-run-center">
 {error&&<p role="alert" className="lab-alert lab-alert-error">{error}</p>}
 {!batch?<><div className="lab-run-heading"><input aria-label="搜索测试运行" type="search" placeholder="搜索团队、用例或模型" value={query} onChange={e=>setQuery(e.target.value)}/><button className="lab-primary" onClick={()=>setCreating(true)}>＋ 创建测试运行</button></div>
 {groups.length?<div className="lab-table-scroll"><table className="lab-comparison-table lab-run-table"><thead><tr><th>测试运行</th><th>团队 / 成员</th><th>用例 / 模型</th><th>执行进度</th><th>验收通过</th><th/></tr></thead><tbody>{groups.filter(([,rs])=>rs.some(r=>`${r.caseName} ${r.model} ${r.teamSnapshot.name}`.includes(query))).map(([id,rs])=>{const done=rs.filter(r=>!isActiveRun(r.status)).length;return <tr key={id}><td><strong>{new Date(rs[0].createdAt).toLocaleString('zh-CN')}</strong><small>批次 {id.slice(0,8)}</small></td><td>{[...new Set(rs.map(r=>r.teamSnapshot.name))].join('、')}<small>{[...new Set(rs.map(r=>r.teamSnapshot.members.find(m=>m.id===r.actorId)?.name??r.actorId))].join('、')}</small></td><td>{new Set(rs.map(r=>r.caseId)).size} 个用例 · {new Set(rs.map(r=>r.model)).size} 个模型</td><td>{done} / {rs.length}<small>{done===rs.length?'已结束':rs.some(r=>r.status==='running')?'运行中':'排队中'}</small></td><td>{rs.filter(r=>scoreRun(r).accepted).length} / {rs.length}</td><td><button onClick={()=>{setBatch(id);setDetail(null);}}>查看结果</button></td></tr>;})}</tbody></table></div>:<Empty title="还没有测试运行">先选择团队、用例和模型，创建第一批测试。</Empty>}</>:
 <><div className="lab-run-heading"><button onClick={()=>{if(detail)setDetail(null);else setBatch(null);}}>← {detail?'返回本次测试':'返回运行列表'}</button><div className="lab-actions">{selected.some(r=>isActiveRun(r.status))&&<button disabled={busy} onClick={()=>void action(async()=>{for(const r of selected.filter(r=>isActiveRun(r.status)))await client.cancel(r.id);})}>取消本批剩余运行</button>}<button onClick={()=>downloadJson(`test-${batch}.json`,selected)}>导出本次结果</button></div></div>
 {run?<article className="lab-run-detail"><h2>{run.caseName}</h2><p className="lab-muted">{run.teamSnapshot.name} · {run.teamSnapshot.members.find(m=>m.id===run.actorId)?.name} · {run.model} · {runLabels[run.status]}</p><RunDetails key={run.id} run={run} busy={busy} onReview={(verdict,note)=>action(()=>client.review(run.id,verdict,note))}/></article>:<><h2>本次测试结果</h2><ComparisonReport runs={selected} onOpenRun={setDetail}/></>}
 </>}
 </section>;
}

function RunComposer({client,bootstrap,initialIds,onCancel,onStart}:{client:ReturnType<typeof createLabClient>;bootstrap:LabBootstrap;initialIds:string[];onCancel:()=>void;onStart:(ids:string[],selection:LabRunSelection,requestId:string)=>Promise<void>}){
 const [stage,setStage]=useState(1);const [casePage,setCasePage]=useState(1);
 const first=bootstrap.state.cases.find(c=>initialIds.includes(c.id));const teams=bootstrap.state.teams.filter(t=>!t.archived);
 const [teamId,setTeam]=useState(first?.teamId??teams[0]?.id??'');const team=teams.find(t=>t.id===teamId);
 const [actor,setActor]=useState(first?.actorId??team?.members[0]?.id??'');
 const [skill,setSkill]=useState(bootstrap.skills.some(s=>s.id===first?.steps[0]?.skillId)?first!.steps[0].skillId:bootstrap.skills[0]?.id??'agentdoor-task-planner');
 const [ids,setIds]=useState(initialIds);const [query,setQuery]=useState('');const [models,setModels]=useState([bootstrap.config.model]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const request=useRef({id:uid(),signature:""});
 const eligible=eligibleCases(bootstrap,teamId,skill,actor);const shown=eligible.filter(c=>`${c.name} ${c.category}`.includes(query));const selected=eligible.filter(c=>ids.includes(c.id));const calls=selected.reduce((n,c)=>n+c.steps.length,0)*models.length;
 const paged=pageSlice(shown,casePage,10);
 function reset(){setCasePage(1);setIds([]);setError('');request.current={id:uid(),signature:""};}
 async function start(){setError('');if(stage!==3||!selected.length||!models.length||!team?.members.some(m=>m.id===actor))return;setBusy(true);try{const signature=JSON.stringify([selected.map(c=>c.id),models,actor]);if(request.current.signature!==signature)request.current={id:uid(),signature};await onStart(selected.map(c=>c.id),{models,actorId:actor},request.current.id);}catch(e){setError(e instanceof Error?e.message:'提交失败');setBusy(false);}}
 return <form className="lab-run-composer" onSubmit={e=>e.preventDefault()}>
 <div className="lab-run-heading"><h2>创建测试运行</h2><button type="button" disabled={busy} onClick={onCancel}>返回运行列表</button></div>
 <ol className="lab-run-steps">{['选择团队','选择用例','选择模型'].map((label,i)=><li key={label} aria-current={stage===i+1?'step':undefined}>{i+1} · {label}</li>)}</ol>
 <fieldset hidden={stage!==1} disabled={busy} className="lab-run-fields"><legend>1 · 选择测试范围</legend><div className="lab-run-scope"><label>团队<FilterSelect label="运行团队" value={teamId} options={teams.map(t=>({value:t.id,label:t.name}))} onChange={id=>{setTeam(id);setActor(teams.find(t=>t.id===id)?.members[0]?.id??'');reset();}}/></label><label>执行成员<FilterSelect label="运行成员" value={actor} options={team?.members.map(m=>({value:m.id,label:`${m.name} · ${m.role}`}))??[]} onChange={id=>{setActor(id);reset();}}/></label><label>测试类型<FilterSelect label="运行测试类型" value={skill} options={bootstrap.skills.map(s=>({value:s.id,label:s.title}))} onChange={id=>{setSkill(id as typeof skill);reset();}}/></label></div><p className="lab-muted">{team?.members.find(m=>m.id===actor)?.responsibilities.join('；')||'该成员尚未填写责任。'}</p></fieldset>
 <p className="lab-muted">{team?.name} · {team?.members.find(m=>m.id===actor)?.name} · {bootstrap.skills.find(s=>s.id===skill)?.title}</p>{ids.some(id=>!eligible.some(c=>c.id===id))&&<p role="status" className="lab-alert">原先选择中有用例不属于当前团队、测试类型或成员可见范围，已排除。请确认下方已选数量。</p>}
 <fieldset hidden={stage!==2} disabled={busy} className="lab-run-fields"><legend>2 · 选择该团队的测试用例</legend><div className="lab-run-heading"><input type="search" aria-label="搜索可选用例" placeholder="搜索用例或分类" value={query} onChange={e=>{setQuery(e.target.value);setCasePage(1);}}/><div className="lab-actions"><button type="button" onClick={()=>setIds([...new Set([...ids,...paged.items.map(c=>c.id)])])}>全选本页</button><button type="button" onClick={()=>setIds([...new Set([...ids,...shown.map(c=>c.id)])])}>全选筛选结果（{shown.length}）</button><button type="button" disabled={!selected.length} onClick={()=>setIds([])}>清空</button><span role="status">已选 {selected.length} 条</span></div></div><div className="lab-run-case-list">{paged.items.map(c=><article key={c.id}><label className="lab-check"><input type="checkbox" checked={ids.includes(c.id)} onChange={e=>setIds(e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id))}/><span>{c.name}<small>{c.category} · {c.steps.length} 步</small></span></label><details><summary>输入与预期</summary>{c.steps.map(s=><div key={s.id}><p>{s.prompt}</p><ul>{(c.verification?.expectedResults.find(r=>r.stepId===s.id)?.criteria??c.reviewChecklist).map((t,i)=><li key={i}>{t}</li>)}</ul><small>Skill 版本：{bootstrap.state.skillVersions?.find(v=>v.id===(s.skillVersionId===null?'':s.skillVersionId||bootstrap.state.skillDefaults?.[s.skillId]))?.label??'工作区版本'}</small></div>)}</details></article>)}{!shown.length&&<Empty title="当前范围没有可运行用例">请切换团队、成员或测试类型，或清空搜索。仅列出该成员有权读取目标任务的用例。</Empty>}</div><Pagination page={paged.current} pages={paged.pages} total={shown.length} onChange={setCasePage}/><p className="lab-muted">跨页保留勾选 · 当前团队与类型共 {eligible.length} 条可运行用例</p></fieldset>
 <fieldset hidden={stage!==3} disabled={busy} className="lab-run-fields"><legend>3 · 选择模型</legend><ModelPicker client={client} configured={bootstrap.config.configured} models={[bootstrap.config.model,...bootstrap.state.models??[]]} value={models} onChange={setModels}/></fieldset>
 {selected.length>bootstrap.config.maxBatchSize&&<p role="alert">单批最多选择 {bootstrap.config.maxBatchSize} 条用例，请缩小选择范围。</p>}{error&&<p role="alert" className="lab-alert lab-alert-error">{error}</p>}{!bootstrap.config.configured&&<p role="alert">请先配置模型 API。</p>}
 <footer className="lab-run-submit"><div><strong>{selected.length} 条用例 × {models.length} 个模型</strong><small>{calls} 次计划调用 · 开始后产生 API 用量，按队列执行</small></div><div className="lab-actions">{stage>1&&<button type="button" disabled={busy} onClick={()=>setStage(stage-1)}>上一步</button>}{stage<3?<button key="next-step" type="button" className="lab-primary" disabled={stage===1?!team?.members.some(m=>m.id===actor):!selected.length||selected.length>bootstrap.config.maxBatchSize} onClick={()=>setStage(stage+1)}>下一步</button>:<button key="start-run" type="button" onClick={()=>void start()} className="lab-primary" disabled={busy||!selected.length||!models.length||!bootstrap.config.configured||selected.length>bootstrap.config.maxBatchSize}>{busy?'正在创建…':'开始运行测试'}</button>}</div></footer>
 </form>;
}
