import React, { useState } from "react";
import { Field } from "./editors";
import { isActiveRun, runLabels } from "./model";
import type { LabCase, LabConfig, LabRun, LabTeam } from "./types";

export function Empty({ title, children }: { title: string; children?: React.ReactNode }) { return <div className="lab-empty"><span className="lab-empty-mark" aria-hidden="true">◇</span><h3>{title}</h3>{children && <p>{children}</p>}</div>; }
export function JsonDetail({ title, value, open = false }: { title: string; value: unknown; open?: boolean }) { return <details className="lab-json-detail" open={open}><summary>{title}</summary><pre>{typeof value === "string" ? value : JSON.stringify(value, null, 2) ?? "未提供"}</pre></details>; }
export function TeamDetails({ team, cases, onEditResponsibility, onOpenCase }: { team: LabTeam; cases?: LabCase[]; onEditResponsibility?: (memberId: string) => void; onOpenCase?: (caseId:string)=>void }) {
  const person = (id: string | null) => team.members.find((member) => member.id === id)?.name || (id ? "不可见成员" : "未指派");
  const recordTime=(value:string)=>value&&!Number.isNaN(new Date(value).getTime())?new Date(value).toLocaleString("zh-CN"):"时间未记录";
  const scopedCases=cases?.filter((item)=>item.teamId===team.id)??[];
  return <>
    <p className="lab-description">{team.description || "暂无团队说明"}</p>
    <section className="lab-detail-section"><h3>成员与责任 <small>{team.members.length}</small></h3>{team.members.map((member) => <article className="lab-member-row" key={member.id}><span className="lab-avatar">{member.name.slice(0, 1)}</span><div className="lab-member-content"><strong>{member.name} <small>{member.role || "未设角色"}</small></strong><p>{member.responsibilities.join("；") || "尚未记录责任范围"}</p></div>{onEditResponsibility && <button type="button" className="lab-member-edit" aria-label={`编辑${member.name}的责任`} onClick={() => onEditResponsibility(member.id)}>编辑责任</button>}</article>)}</section>
    <section className="lab-detail-section"><h3>任务 <small>{team.tasks.length}</small></h3>{!team.tasks.length && <p className="lab-muted">当前范围暂无任务。</p>}{team.tasks.map((task) => <details key={task.id} className="lab-task-row"><summary><span className={`lab-status status-${task.status}`}>{task.status}</span><strong>{task.parentId && <span className="lab-muted">↳ </span>}{task.title}</strong><small>{person(task.ownerId)}</small></summary><div className="lab-task-content">
      <p>{task.goal || "未填写任务目的"}</p><dl className="lab-facts"><div><dt>创建人</dt><dd>{task.createdById?person(task.createdById):"历史数据未记录"}</dd></div><div><dt>负责人</dt><dd>{person(task.ownerId)}</dd></div><div><dt>参与人</dt><dd>{task.participantIds.map(person).join("、") || "无"}</dd></div><div><dt>预计工时</dt><dd>{task.estimatedMinutes === null ? "未估算" : `${task.estimatedMinutes} 分钟`}</dd></div><div><dt>可见范围</dt><dd>{task.visibility === "team" ? "团队公开" : "限定人员"}</dd></div><div><dt>父任务</dt><dd>{task.parentId ? team.tasks.find((item) => item.id === task.parentId)?.title || "不可见任务" : "无"}</dd></div><div><dt>前置任务</dt><dd>{task.dependsOnTaskIds.map((id) => team.tasks.find((item) => item.id === id)?.title || "不可见任务").join("、") || "无"}</dd></div><div><dt>截止时间</dt><dd>{task.dueAt ? new Date(task.dueAt).toLocaleString("zh-CN") : "未设置"}</dd></div><div><dt>标签</dt><dd>{task.tags.join("、") || "无"}</dd></div></dl>
      <h4>完成标准</h4><TextList items={task.acceptanceCriteria} /><h4>执行建议</h4><TextList items={task.executionTips} />
      {(["文件","讨论","其他"] as const).map((group)=>{const items=team.evidence.filter((item)=>item.taskId===task.id&&(group==="其他"?["交付","确认"].includes(item.kind):item.kind===group));const title=group==="文件"?"任务文件":group==="讨论"?"任务讨论":"交付与确认记录";return <section className="lab-record-group" key={group}><h4>{title} <small>{items.length}</small></h4>{items.length?items.map((item)=><article className="lab-record-row" key={item.id}><header><strong>{item.title||`${item.kind}记录`}</strong><small>{item.kind} · {person(item.authorId)} · {recordTime(item.createdAt)}</small></header><p>{item.content||"未填写内容"}</p></article>):<p className="lab-muted">暂无{title}</p>}</section>;})}
    </div></details>)}</section>
    {cases&&<section className="lab-detail-section"><h3>该团队的测试用例 <small>{scopedCases.length}</small></h3>{scopedCases.length?scopedCases.map((item)=><button type="button" className="lab-linked-case" key={item.id} onClick={()=>onOpenCase?.(item.id)}><span><strong>{item.name}</strong><small>{person(item.actorId)}视角 · {item.steps.length} 步{!item.enabled&&" · 已停用"}</small></span><span>查看用例 →</span></button>):<p className="lab-muted">该团队还没有测试用例。</p>}</section>}
  </>;
}
export function TextList({ items }: { items: string[] }) { return items.length ? <ul className="lab-text-list">{items.map((text, index) => <li key={index}>{text}</li>)}</ul> : <p className="lab-muted">未设置</p>; }
export function CaseDetails({ item, team, skills }: { item: LabCase; team?: LabTeam; skills: { id: string; title: string }[] }) {
  return <><p className="lab-description">{item.description || "暂无用例说明"}</p><dl className="lab-facts"><div><dt>所属团队</dt><dd>{team?.name || "团队不存在"}</dd></div><div><dt>执行成员视角</dt><dd>{team?.members.find((member) => member.id === item.actorId)?.name || "成员不存在"}</dd></div><div><dt>启用状态</dt><dd>{item.enabled ? "已启用" : "已停用"}{item.archived && " · 已归档"}</dd></div><div><dt>用例版本</dt><dd>v{item.version}</dd></div></dl>
    <section className="lab-detail-section"><h3>执行步骤 <small>{item.steps.length}</small></h3>{item.steps.map((step, index) => <article className="lab-step-preview" key={step.id}><header><span className="lab-step-index">{index + 1}</span><strong>{skills.find((skill) => skill.id === step.skillId)?.title || step.skillId}</strong></header><p>{step.prompt || "未填写输入"}</p><small>{step.taskId ? team?.tasks.find((task) => task.id === step.taskId)?.title || "目标任务不可用" : "全部可见任务 / 规划新任务"}{step.usePreviousOutput && " · 使用前一步输出"}{step.events.length > 0 && ` · ${step.events.length} 个前置事件`}</small>{step.events.length > 0 && <JsonDetail title="查看前置事件" value={step.events} />}</article>)}</section>
    <section className="lab-detail-section"><h3>自动断言 <small>{item.assertions.length}</small></h3>{item.assertions.map((assertion) => <div key={assertion.id} className="lab-assertion-preview"><strong>{assertion.label}</strong><code>{assertion.path || "整个输出"} · {assertion.operator} {assertion.operator === "exists" ? "" : JSON.stringify(assertion.expected)}</code></div>)}{!item.assertions.length && <p className="lab-muted">未设置自动断言</p>}</section>
    <section className="lab-detail-section"><h3>人工核对项</h3><TextList items={item.reviewChecklist} /></section>
    {item.origin && <p className="lab-muted">来源：{item.origin}</p>}{item.legacyInput && <><p className="lab-alert">历史用例仅作为资料迁移，默认停用待复核。原始输入与预期不会自动发送给模型；请在编辑器中明确配置步骤、任务和断言后再启用。旧版模拟提交与 ACL 情节尚未实现，不能据此判定已通过。</p><JsonDetail title="原始用例输入（只读）" value={item.legacyInput} /></>}{item.legacyExpected !== undefined && <JsonDetail title="原始期望（只读）" value={item.legacyExpected} />}
  </>;
}
export function RunDetails({ run, onReview, busy }: { run: LabRun; onReview: (verdict: "passed" | "failed", note: string) => Promise<void>; busy: boolean }) {
  const [note, setNote] = useState(run.review?.note || "");
  const [checked, setChecked] = useState<string[]>([]);
  const elapsed = run.steps.reduce((sum, step) => sum + step.durationMs, 0);
  const hasUsage = run.steps.length > 0 && run.steps.every((step) => step.usage.totalTokens !== null);
  return <>
    <dl className="lab-facts"><div><dt>运行状态</dt><dd>{runLabels[run.status]}</dd></div><div><dt>模型</dt><dd>{run.model || "未提供"}</dd></div><div><dt>创建时间</dt><dd>{new Date(run.createdAt).toLocaleString("zh-CN")}</dd></div><div><dt>模型调用耗时</dt><dd>{run.steps.length ? `${(elapsed / 1000).toFixed(1)} 秒` : "等待结果"}</dd></div><div><dt>Total Tokens</dt><dd>{hasUsage ? run.steps.reduce((sum, step) => sum + (step.usage.totalTokens || 0), 0).toLocaleString() : "未提供 / 等待结果"}</dd></div><div><dt>用例版本</dt><dd>v{run.caseSnapshot.version}</dd></div></dl>
    {run.error && <p role="alert" className="lab-alert lab-alert-error">{run.error}</p>}
    {!run.steps.length && <Empty title={isActiveRun(run.status) ? "等待模型返回" : "没有步骤结果"}>运行报告保留本次快照；活动运行每 2 秒刷新。</Empty>}
    {run.steps.map((step, index) => <section className="lab-detail-section" key={step.stepId}><h3>步骤 {index + 1} <small>{step.skillId}</small></h3><div className="lab-step-meta"><span>结构检查：{step.structure === "passed" ? "通过" : step.structure === "failed" ? "失败" : "未判定"}</span><span>{(step.durationMs / 1000).toFixed(1)} 秒</span><span>输入 {step.usage.inputTokens ?? "未知"} / 输出 {step.usage.outputTokens ?? "未知"} Tokens</span></div>
      {step.error && <p className="lab-alert lab-alert-error">{step.error}</p>}{step.structureErrors.length > 0 && <TextList items={step.structureErrors} />}
      <JsonDetail title="实际输入" value={step.input} /><JsonDetail title="首次输出（原始返回）" value={step.rawOutput || "未返回内容"} open /><JsonDetail title="结构化输出" value={step.output} />
      <h4>自动断言</h4>{step.assertions.length ? step.assertions.map((assertion) => <details key={assertion.id} className="lab-assertion-result"><summary><span className={`lab-status status-${assertion.status}`}>{assertion.status === "passed" ? "通过" : assertion.status === "failed" ? "失败" : "未判定"}</span>{assertion.label}</summary><p>{assertion.message}</p><JsonDetail title="实际值" value={assertion.actual} /><JsonDetail title="期望值" value={assertion.expected} /></details>) : <p className="lab-muted">此步骤没有自动断言</p>}
      <details className="lab-snapshot"><summary>前后沙箱对照</summary><div className="lab-snapshot-grid"><div><h4>执行前</h4><TeamDetails team={step.before} /></div><div><h4>执行后</h4><TeamDetails team={step.after} /></div></div><JsonDetail title="执行前完整快照" value={step.before} /><JsonDetail title="执行后完整快照" value={step.after} /></details>
      <details className="lab-json-detail"><summary>技能与提示词版本</summary><dl className="lab-facts"><div><dt>Skill hash</dt><dd><code>{step.skillHash}</code></dd></div><div><dt>Prompt hash</dt><dd><code>{step.promptHash}</code></dd></div></dl>{step.skillSnapshot && <pre>{step.skillSnapshot}</pre>}</details>
    </section>)}
    <section className="lab-detail-section"><h3>人工核对</h3><p className="lab-muted">自动断言不代替人工判断；本区复核不会修改首次输出。</p>{run.caseSnapshot.reviewChecklist.map((item, index) => <label className="lab-check" key={index}><input type="checkbox" checked={checked.includes(String(index))} onChange={(event) => setChecked(event.target.checked ? [...checked, String(index)] : checked.filter((id) => id !== String(index)))} />{item}</label>)}
      {!run.caseSnapshot.reviewChecklist.length && <p className="lab-muted">此用例没有预设人工核对项。</p>}
      <Field label="人工核对备注"><textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} placeholder="记录判断依据、遗漏或需要修正的问题" /></Field>
      {run.review && <p className="lab-alert">已标记为{run.review.verdict === "passed" ? "通过" : "失败"} · {new Date(run.review.at).toLocaleString("zh-CN")}<br />{run.review.note || "无备注"}</p>}
      <div className="lab-actions"><button type="button" disabled={busy || isActiveRun(run.status) || checked.length !== run.caseSnapshot.reviewChecklist.length} onClick={() => void onReview("passed", note)}>人工标记通过</button><button type="button" disabled={busy || isActiveRun(run.status)} onClick={() => void onReview("failed", note)}>人工标记失败</button></div>
    </section>
    <JsonDetail title="本次用例快照" value={run.caseSnapshot} /><JsonDetail title="初始团队快照" value={run.teamSnapshot} />
  </>;
}
export function ConfigDetails({ config }: { config: LabConfig }) { return <div className="lab-settings"><p className="lab-alert">仅展示服务端返回的脱敏配置。API Key 不进入浏览器；此页面不会调用模型做连接测试。</p><dl className="lab-facts"><div><dt>PPIO 连接</dt><dd>{config.configured ? "服务端已配置（尚不代表请求成功）" : "未配置，请在服务端设置"}</dd></div><div><dt>模型</dt><dd>{config.model || "未设置"}</dd></div><div><dt>接口地址</dt><dd>{config.endpoint || "未设置"}</dd></div><div><dt>单批上限</dt><dd>{config.maxBatchSize} 个用例</dd></div><div><dt>最大输出</dt><dd>{config.maxOutputTokens} Tokens</dd></div><div><dt>调用超时</dt><dd>{config.timeoutMs / 1000} 秒</dd></div><div><dt>隔离存储</dt><dd>{config.storage}</dd></div></dl><section className="lab-detail-section"><h3>运行边界</h3><TextList items={["团队、任务、证据及报告只保存到独立测试存储，不修改 AgentDoor 业务数据。", "点击运行后才会发起真实 PPIO 请求，可能产生费用。", "自动化断言、模型原始输出和人工核对结果分别保留。", "中断和取消不保证上游停止计费。"]} /></section></div>; }
