import { VerificationSummary } from "./verification";
import React, { useState } from "react";
import { Field } from "./editors";
import { isActiveRun, runLabels } from "./model";
import type { LabCase, LabConfig, LabRun, LabTeam, LabState } from "./types";
import { DocumentView } from "./markdown";
import { evidenceDownload, isMarkdownEvidence } from "./markdown-files";
import { CaseContext } from "./case-context";

export function Empty({ title, children }: { title: string; children?: React.ReactNode }) { return <div className="lab-empty"><span className="lab-empty-mark" aria-hidden="true">◇</span><h3>{title}</h3>{children && <p>{children}</p>}</div>; }
export function JsonDetail({ title, value, open = false }: { title: string; value: unknown; open?: boolean }) { return <details className="lab-json-detail" open={open}><summary>{title}</summary><pre>{typeof value === "string" ? value : JSON.stringify(value, null, 2) ?? "未提供"}</pre></details>; }
export function TeamDetails({ team, cases, onEditResponsibility, onOpenCase, onEditMember, onAddMember, onEditTask, onEditFile, onAddChild, onSwitchActor, actorId, onRunCase }: { onEditMember?:(id:string)=>void;onAddMember?:()=>void;onEditTask?:(id:string)=>void;onEditFile?:(id:string)=>void;onAddChild?:(id:string)=>void;onSwitchActor?:(id:string)=>void;actorId?:string;onRunCase?:(id:string)=>void;team: LabTeam; cases?: LabCase[]; onEditResponsibility?: (memberId: string) => void; onOpenCase?: (caseId:string)=>void }) {
  const [taskFilter,setTaskFilter]=useState("all");
  const [taskSearch,setTaskSearch]=useState("");
  const ordered: {task:LabTeam["tasks"][number];depth:number}[]=[];const seen=new Set<string>();
  const walk=(parent:string|null,depth:number)=>{for(const task of team.tasks.filter(t=>t.parentId===parent)){if(seen.has(task.id))continue;seen.add(task.id);ordered.push({task,depth});walk(task.id,depth+1);}};walk(null,0);for(const task of team.tasks)if(!seen.has(task.id))ordered.push({task,depth:0});
  const visibleTasks=ordered.filter(({task})=>(!taskSearch||`${task.title} ${task.goal}`.includes(taskSearch))&&(taskFilter==="all"||taskFilter==="owner"&&task.ownerId===actorId||taskFilter==="participant"&&task.participantIds.includes(actorId??"")||taskFilter==="blocked"&&task.status==="已阻塞"));
  const person = (id: string | null) => team.members.find((member) => member.id === id)?.name || (id ? "不可见成员" : "未指派");
  const recordTime=(value:string)=>value&&!Number.isNaN(new Date(value).getTime())?new Date(value).toLocaleString("zh-CN"):"时间未记录";
  const scopedCases=cases?.filter((item)=>item.teamId===team.id)??[];
  return <>
    <p className="lab-description">{team.description || "暂无团队说明"}</p>
    <p className="lab-muted lab-team-data-counts">{(["文件","讨论","交付","确认","活动"] as const).map(kind=><span key={kind}>{kind} {team.evidence.filter(item=>item.kind===kind).length}</span>)}</p>
    <section className="lab-detail-section"><div className="lab-section-heading"><h3>成员与责任 <small>{team.members.length}</small></h3>{onAddMember&&<button onClick={onAddMember}>＋ 添加成员</button>}</div>{team.members.map((member) => <article className="lab-member-row" key={member.id}><span className="lab-avatar">{member.name.slice(0, 1)}</span><div className="lab-member-content"><strong>{member.name} <small>{member.role || "未设角色"}</small></strong><p>{member.responsibilities.join("；") || "尚未记录责任范围"}</p></div>{onSwitchActor&&<button onClick={()=>onSwitchActor(member.id)}>切换视角</button>}{onEditMember&&<button onClick={()=>onEditMember(member.id)}>编辑人员</button>}{onEditResponsibility && <button type="button" className="lab-member-edit" aria-label={`编辑${member.name}的责任`} onClick={() => onEditResponsibility(member.id)}>编辑责任</button>}</article>)}</section>
    <section className="lab-detail-section"><h3>任务 <small>{team.tasks.length}</small></h3>{!team.tasks.length && <p className="lab-muted">当前范围暂无任务。</p>}<div className="lab-task-tools"><input type="search" aria-label="搜索任务" placeholder="搜索任务" value={taskSearch} onChange={e=>setTaskSearch(e.target.value)}/><select aria-label="任务范围" value={taskFilter} onChange={e=>setTaskFilter(e.target.value)}><option value="all">全部可见任务</option><option value="blocked">已阻塞</option>{actorId&&<><option value="owner">我负责的</option><option value="participant">我参与的</option></>}</select></div>{!visibleTasks.length&&team.tasks.length>0&&<p className="lab-muted">没有符合条件的任务。</p>}{visibleTasks.map(({task,depth}) => <details style={{marginLeft:Math.min(depth,3)*14}} key={task.id} className="lab-task-row"><summary><span className={`lab-status status-${task.status}`}>{task.status}</span><strong>{task.parentId && <span className="lab-muted">↳ </span>}{task.title}</strong><small>{person(task.ownerId)}</small></summary><div className="lab-task-content">
      <div className="lab-actions">{onEditTask&&<button onClick={()=>onEditTask(task.id)}>编辑任务、文件与动态</button>}{onAddChild&&<button onClick={()=>onAddChild(task.id)}>＋ 添加子任务</button>}</div><p>{task.goal || "未填写任务目的"}</p><dl className="lab-facts"><div><dt>创建人</dt><dd>{task.createdById?person(task.createdById):"历史数据未记录"}</dd></div><div><dt>负责人</dt><dd>{person(task.ownerId)}</dd></div><div><dt>参与人</dt><dd>{task.participantIds.map(person).join("、") || "无"}</dd></div><div><dt>预计工时</dt><dd>{task.estimatedMinutes === null ? "未估算" : `${task.estimatedMinutes} 分钟`}</dd></div><div><dt>可见范围</dt><dd>{task.visibility === "team" ? "团队公开" : "限定人员"}</dd></div><div><dt>父任务</dt><dd>{task.parentId ? team.tasks.find((item) => item.id === task.parentId)?.title || "不可见任务" : "无"}</dd></div><div><dt>前置任务</dt><dd>{task.dependsOnTaskIds.map((id) => team.tasks.find((item) => item.id === id)?.title || "不可见任务").join("、") || "无"}</dd></div><div><dt>截止时间</dt><dd>{task.dueAt ? new Date(task.dueAt).toLocaleString("zh-CN") : "未设置"}</dd></div><div><dt>标签</dt><dd>{task.tags.join("、") || "无"}</dd></div></dl>
      <h4>子任务 · {team.tasks.filter(t=>t.parentId===task.id).length}</h4>{team.tasks.filter(t=>t.parentId===task.id).map(child=><p className="lab-subtask-line" key={child.id}><span>{child.status}</span>{child.title}<small>{person(child.ownerId)}</small></p>)}<h4>完成标准</h4><TextList items={task.acceptanceCriteria} /><h4>执行建议</h4><TextList items={task.executionTips} />
      {(["文件","动态"] as const).map((group)=>{const items=team.evidence.filter((item)=>item.taskId===task.id&&(group==="动态"?item.kind!=="文件":item.kind==="文件")).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const title=group==="文件"?"任务文件":"任务动态 · 讨论、交付、确认与活动";return <section className="lab-record-group" key={group}><h4>{title} <small>{items.length}</small></h4>{items.length?items.map((item)=><article className="lab-record-row" id={`lab-record-${item.id}`} key={item.id}><header><strong>{item.title||`${item.kind}记录`}</strong><small>{item.kind} · {person(item.authorId)} · {recordTime(item.createdAt)}</small></header><div className="lab-record-references">{[...(item.replyToId?[{id:item.replyToId,label:"回复"}]:[]),...(item.supersedesId?[{id:item.supersedesId,label:"替代版本"}]:[]),...(item.relatedEvidenceIds??[]).map(id=>({id,label:"关联资料"}))].map(ref=>{const related=team.evidence.find(e=>e.id===ref.id);return related?<a key={`${ref.label}-${ref.id}`} href={`#lab-record-${ref.id}`}>{ref.label}：{related.title}</a>:null;})}</div>{isMarkdownEvidence(item)?<DocumentView content={item.content} filename={item.attachment?.name||item.title} onEdit={onEditFile?()=>onEditFile(item.id):undefined}/>:<><p>{item.content||"未填写内容"}</p>{item.kind==="文件"&&<a href={evidenceDownload(item).dataUrl} download={evidenceDownload(item).name}>下载{item.attachment?"附件":"文件内容"}</a>}</>}</article>):<p className="lab-muted">暂无{title}</p>}</section>;})}
    </div></details>)}</section>
    {cases&&<section className="lab-detail-section"><h3>该团队的测试用例 <small>{scopedCases.length}</small></h3>{scopedCases.length?scopedCases.map((item)=><div className="lab-linked-case" key={item.id}><span><strong>{item.name}</strong><small>{person(item.actorId)}视角 · {item.steps.length} 步{!item.enabled&&" · 已停用"}</small></span><div className="lab-actions">{onRunCase&&<button disabled={!item.enabled||item.archived||team.archived} onClick={()=>onRunCase(item.id)}>以当前人员运行</button>}<button onClick={()=>onOpenCase?.(item.id)}>查看用例 →</button></div></div>):<p className="lab-muted">该团队还没有测试用例。</p>}</section>}
  </>;
}
export function TextList({ items }: { items: string[] }) { return items.length ? <ul className="lab-text-list">{items.map((text, index) => <li key={index}>{text}</li>)}</ul> : <p className="lab-muted">未设置</p>; }
export function CaseDetails({ item, team, skills, versions = [], defaults = {}, onEditFile }: { item: LabCase; team?: LabTeam; skills: { id: string; title: string }[];versions?:LabState["skillVersions"];defaults?:LabState["skillDefaults"];onEditFile?:(id:string)=>void }) {
  return <><p className="lab-description">{item.description || "暂无用例说明"}</p><dl className="lab-facts"><div><dt>所属团队</dt><dd>{team?.name || "团队不存在"}</dd></div><div><dt>执行成员视角</dt><dd>{team?.members.find((member) => member.id === item.actorId)?.name || "成员不存在"}</dd></div><div><dt>启用状态</dt><dd>{item.enabled ? "已启用" : "已停用"}{item.archived && " · 已归档"}</dd></div><div><dt>用例版本</dt><dd>v{item.version}</dd></div></dl>
    <VerificationSummary item={item} /><section className="lab-detail-section"><h3>执行步骤 <small>{item.steps.length}</small></h3>{item.steps.map((step, index) => <article className="lab-step-preview" key={step.id}><header><span className="lab-step-index">{index + 1}</span><strong>{skills.find((skill) => skill.id === step.skillId)?.title || step.skillId}</strong></header><small>Skill 版本：{step.skillVersionId===null?"工作区版本":versions.find(v=>v.id===(step.skillVersionId||defaults[step.skillId]))?.label||"工作区版本"}{step.skillVersionId===undefined&&" · 跟随默认"}</small><p>{step.prompt || "未填写输入"}</p>{step.evaluatedAt&&<p className="lab-muted">固定判断时间：{new Date(step.evaluatedAt).toLocaleString("zh-CN")}</p>}<small>{step.taskId ? team?.tasks.find((task) => task.id === step.taskId)?.title || "目标任务不可用" : "全部可见任务 / 规划新任务"}{step.usePreviousOutput && " · 使用前一步输出"}{step.events.length > 0 && ` · ${step.events.length} 个前置事件`}</small>{step.events.length > 0 && <JsonDetail title="查看前置事件" value={step.events} />}</article>)}</section>
    {team?.members.some(member=>member.id===item.actorId) && <CaseContext key={`${item.id}-${item.actorId}`} item={item} team={team} onEditFile={onEditFile} />}
    <section className="lab-detail-section"><h3>自动断言 <small>{item.assertions.length}</small></h3>{item.assertions.map((assertion) => <div key={assertion.id} className="lab-assertion-preview"><strong>{assertion.label}</strong><code>{assertion.path || "整个输出"} · {assertion.operator} {assertion.operator === "exists" ? "" : JSON.stringify(assertion.expected)}</code></div>)}{!item.assertions.length && <p className="lab-muted">未设置自动断言</p>}</section>
    <section className="lab-detail-section"><h3>人工核对项</h3><TextList items={item.reviewChecklist} /></section>
    {item.origin && <JsonDetail title="用例来源（只读）" value={item.origin} />}{item.legacyInput && <><p className="lab-alert">历史用例仅作为资料迁移，默认停用待复核。原始输入与预期不会自动发送给模型；请在编辑器中明确配置步骤、任务和断言后再启用。旧版模拟提交与 ACL 情节尚未实现，不能据此判定已通过。</p><JsonDetail title="原始用例输入（只读）" value={item.legacyInput} /></>}{item.legacyExpected !== undefined && <JsonDetail title="原始期望（只读）" value={item.legacyExpected} />}
  </>;
}
export function RunDetails({ run, onReview, busy }: { run: LabRun; onReview: (verdict: "passed" | "failed", note: string) => Promise<void>; busy: boolean }) {
  const [note, setNote] = useState(run.review?.note || "");
  const [checked, setChecked] = useState<string[]>([]);
  const elapsed = run.steps.reduce((sum, step) => sum + step.durationMs, 0);
  const hasUsage = run.steps.length > 0 && run.steps.every((step) => step.usage.totalTokens !== null);
  return <>
    <dl className="lab-facts"><div><dt>执行人员</dt><dd>{run.teamSnapshot.members.find(m=>m.id===run.actorId)?.name||run.actorId}</dd></div><div><dt>运行状态</dt><dd>{runLabels[run.status]}</dd></div><div><dt>模型</dt><dd>{run.model || "未提供"}</dd></div><div><dt>创建时间</dt><dd>{new Date(run.createdAt).toLocaleString("zh-CN")}</dd></div><div><dt>模型调用耗时</dt><dd>{run.steps.length ? `${(elapsed / 1000).toFixed(1)} 秒` : "等待结果"}</dd></div><div><dt>Total Tokens</dt><dd>{hasUsage ? run.steps.reduce((sum, step) => sum + (step.usage.totalTokens || 0), 0).toLocaleString() : "未提供 / 等待结果"}</dd></div><div><dt>用例版本</dt><dd>v{run.caseSnapshot.version}</dd></div></dl>
    {run.error && <p role="alert" className="lab-alert lab-alert-error">{run.error}</p>}
    {!run.steps.length && <Empty title={isActiveRun(run.status) ? "等待模型返回" : "没有步骤结果"}>运行报告保留本次快照；活动运行每 2 秒刷新。</Empty>}
    {run.steps.map((step, index) => <section className="lab-detail-section" key={step.stepId}><h3>步骤 {index + 1} <small>{step.skillId}</small></h3><div className="lab-step-meta"><span>结构检查：{step.structure === "passed" ? "通过" : step.structure === "failed" ? "失败" : "未判定"}</span><span>{(step.durationMs / 1000).toFixed(1)} 秒</span><span>输入 {step.usage.inputTokens ?? "未知"} / 输出 {step.usage.outputTokens ?? "未知"} Tokens</span></div>
      {step.error && <p className="lab-alert lab-alert-error">{step.error}</p>}{step.structureErrors.length > 0 && <TextList items={step.structureErrors} />}
      <JsonDetail title="实际输入" value={step.input} /><JsonDetail title="首次输出（原始返回）" value={step.rawOutput || "未返回内容"} open /><JsonDetail title="结构化输出" value={step.output} />
      <h4>自动断言</h4>{step.assertions.length ? step.assertions.map((assertion) => <details key={assertion.id} className="lab-assertion-result"><summary><span className={`lab-status status-${assertion.status}`}>{assertion.status === "passed" ? "通过" : assertion.status === "failed" ? "失败" : "未判定"}</span>{assertion.label}</summary><p>{assertion.message}</p><JsonDetail title="实际值" value={assertion.actual} /><JsonDetail title="期望值" value={assertion.expected} /></details>) : <p className="lab-muted">此步骤没有自动断言</p>}
      <details className="lab-snapshot"><summary>前后沙箱对照</summary><div className="lab-snapshot-grid"><div><h4>执行前</h4><TeamDetails team={step.before} /></div><div><h4>执行后</h4><TeamDetails team={step.after} /></div></div><JsonDetail title="执行前完整快照" value={step.before} /><JsonDetail title="执行后完整快照" value={step.after} /></details>
      <details className="lab-json-detail"><summary>技能与提示词版本</summary><dl className="lab-facts"><div><dt>Skill 版本</dt><dd>{step.skillVersionLabel||"工作区版本"}</dd></div><div><dt>Skill hash</dt><dd><code>{step.skillHash}</code></dd></div><div><dt>Prompt hash</dt><dd><code>{step.promptHash}</code></dd></div></dl>{step.skillSnapshot && <pre>{step.skillSnapshot}</pre>}</details>
    </section>)}
    <section className="lab-detail-section"><h3>人工核对</h3><p className="lab-muted">自动断言不代替人工判断；本区复核不会修改首次输出。</p>{run.caseSnapshot.reviewChecklist.map((item, index) => <label className="lab-check" key={index}><input type="checkbox" checked={checked.includes(String(index))} onChange={(event) => setChecked(event.target.checked ? [...checked, String(index)] : checked.filter((id) => id !== String(index)))} />{item}</label>)}
      {!run.caseSnapshot.reviewChecklist.length && <p className="lab-muted">此用例没有预设人工核对项。</p>}
      <Field label="人工核对备注"><textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} placeholder="记录判断依据、遗漏或需要修正的问题" /></Field>
      {run.review && <p className="lab-alert">已标记为{run.review.verdict === "passed" ? "通过" : "失败"} · {new Date(run.review.at).toLocaleString("zh-CN")}<br />{run.review.note || "无备注"}</p>}
      <div className="lab-actions"><button type="button" disabled={busy || isActiveRun(run.status) || checked.length !== run.caseSnapshot.reviewChecklist.length} onClick={() => void onReview("passed", note)}>人工标记通过</button><button type="button" disabled={busy || isActiveRun(run.status)} onClick={() => void onReview("failed", note)}>人工标记失败</button></div>
    </section>
    <JsonDetail title="本次用例快照" value={run.caseSnapshot} /><JsonDetail title="初始团队快照" value={run.teamSnapshot} />
  </>;
}
export function ConfigDetails({ config }: { config: LabConfig }) { return <div className="lab-settings"><p className="lab-alert">仅展示服务端返回的脱敏配置。API Key 不进入浏览器；此页面不会调用模型做连接测试。</p><dl className="lab-facts"><div><dt>PPIO 连接</dt><dd>{config.configured ? "服务端已配置（尚不代表请求成功）" : "未配置，请在服务端设置"}</dd></div><div><dt>模型</dt><dd>{config.model || "未设置"}</dd></div><div><dt>接口地址</dt><dd>{config.endpoint || "未设置"}</dd></div><div><dt>单批上限</dt><dd>{config.maxBatchSize} 个用例</dd></div><div><dt>最大输出</dt><dd>{config.maxOutputTokens} Tokens</dd></div><div><dt>调用超时</dt><dd>{config.timeoutMs / 1000} 秒</dd></div><div><dt>隔离存储</dt><dd>{config.storage}</dd></div></dl><section className="lab-detail-section"><h3>运行边界</h3><TextList items={["团队、任务、证据及报告只保存到独立测试存储，不修改 TaskDoor 业务数据。", "点击运行后才会发起真实 PPIO 请求，可能产生费用。", "自动化断言、模型原始输出和人工核对结果分别保留。", "中断和取消不保证上游停止计费。"]} /></section></div>; }
