import { FileText, ShieldCheck } from "lucide-react";
import type { EnterpriseSource } from "./SourcesList";

type ResourceFormat = "pdf" | "docx" | "patch";
type ResourceBlock =
  | { kind: "heading"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "callout"; label: string; text: string }
  | { kind: "list"; items: string[] }
  | { kind: "table"; rows: string[][] }
  | { kind: "code"; text: string };

type ResourceDocument = {
  eyebrow: string;
  format: ResourceFormat;
  page: string;
  updated: string;
  blocks: ResourceBlock[];
};

const resourceDocuments: Record<string, ResourceDocument> = {
  schema: {
    eyebrow: "零售业务资源库 / POS / 业务规则",
    format: "pdf",
    page: "12 / 28",
    updated: "周岚更新于 2 天前",
    blocks: [
      { kind: "callout", label: "文档信息", text: "文档编号 RTL-POS-COUPON-032 · 版本 v3.2 · 2026-03-01 生效 · 零售交易产品组维护" },
      { kind: "heading", text: "4.3 优惠券核销的一致性" },
      { kind: "paragraph", text: "门店 POS 在收银交易进入 Completed 状态后发起优惠券核销。对于同一个 transaction_id 与 coupon_instance_id 组合，核销服务必须生成唯一且可重复读取的 redemption_record。任何网络超时、客户端重试或离线队列重放，都不得产生第二次券权益扣减。" },
      { kind: "table", rows: [["字段", "来源", "约束"], ["transaction_id", "POS 交易服务", "全局唯一，不可复用"], ["coupon_instance_id", "会员券服务", "一张券对应一个实例"], ["redemption_key", "核销服务", "由交易与券实例稳定派生"]] },
      { kind: "heading", text: "4.3.2 退款与撤单" },
      { kind: "paragraph", text: "全额退款必须引用原核销记录完成券状态恢复。撤单发生在交易日结之前时，系统应先确认支付撤销成功，再将券实例恢复为 Available。部分退款、跨日撤单和人工恢复应记录操作人、原核销记录及恢复原因。" },
      { kind: "callout", label: "待业务确认", text: "部分退款与跨日撤单是否必须沿用原 redemption_key，当前版本未明确。该项正在“评审并灰度验证 POS 优惠券重复核销修复草案”中由 POS 交易域负责人确认。" },
      { kind: "heading", text: "4.4 离线交易重试" },
      { kind: "paragraph", text: "离线队列恢复联网后，交易按 created_at 与 local_sequence 排序上传。请求必须携带离线期间生成的原始交易标识，不得在每次重试时重新生成。" },
      { kind: "list", items: ["单笔交易最多自动重试 5 次，指数退避上限为 30 分钟", "服务端已存在核销记录时直接返回首次处理结果", "异常记录进入 manual_review 队列，禁止 POS 端直接重置券状态"] },
    ],
  },
  incident: {
    eyebrow: "零售技术资源库 / 事故复盘",
    format: "docx",
    page: "3 / 9",
    updated: "陈默更新于 4 个月前",
    blocks: [
      { kind: "table", rows: [["事故编号", "INC-2026-0518"], ["事故级别", "P1"], ["发生时间", "2026-05-18 09:42–11:26"], ["影响范围", "3 家门店 / 17 笔交易 / 11 名会员"], ["复盘拥有者", "零售技术平台组"]] },
      { kind: "heading", text: "2. 事故摘要" },
      { kind: "paragraph", text: "5 月 18 日早高峰期间，华东区域三家门店恢复联网后集中上传离线交易。监控于 09:47 检测到 coupon.redeem.success 数量超过交易完成数，当班 SRE 于 09:55 暂停 offline-replay-consumer，并冻结受影响券实例。" },
      { kind: "list", items: ["09:42：门店 S021、S114、S309 恢复联网", "09:47：优惠券核销成功数超过交易完成数", "09:55：暂停自动重放队列", "10:31：完成影响订单核对与券状态冻结", "11:26：人工恢复完成，业务恢复正常"] },
      { kind: "heading", text: "3.2 已确认根因" },
      { kind: "paragraph", text: "离线交易首次进入本地队列时只持久化 transaction_id，未保留核销请求的 request_id。每次重放均由客户端生成新标识，核销服务因此无法命中首次处理结果，同一 coupon_instance_id 被重复消费。" },
      { kind: "heading", text: "4. 处置与遗留问题" },
      { kind: "paragraph", text: "团队根据原始交易记录逐笔恢复券状态，客服向 11 名会员发送结果通知，未发生实际资金损失。后续需要统一退款、撤单与离线重放的幂等语义，并补齐异常路径自动化测试。" },
      { kind: "callout", label: "遗留决策", text: "退款、撤单是否共用原核销键，以及人工恢复允许重置 Redeemed、Frozen 中的哪些状态，仍需业务拥有者确认。" },
    ],
  },
  commit: {
    eyebrow: "AI 工作成果库 / 候选修复",
    format: "patch",
    page: "3 files changed",
    updated: "由你的 Codex 刚刚上传",
    blocks: [
      { kind: "callout", label: "变更摘要", text: "commit 8f30c1a · 46 insertions · 12 deletions · generated by Codex · awaiting review" },
      { kind: "heading", text: "src/coupon/retry-handler.ts" },
      { kind: "code", text: "@@ -42,12 +42,24 @@ export async function replayCoupon(request) {\n-  const requestId = randomUUID();\n+  const idempotencyKey = createRedemptionKey(\n+    request.transactionId,\n+    request.couponInstanceId,\n+  );\n \n   const result = await couponService.redeem({\n     ...request,\n-    requestId,\n+    idempotencyKey,\n   });\n+\n+  replayLog.attach({\n+    idempotencyKey,\n+    source: 'offline-queue',\n+    originalCreatedAt: request.createdAt,\n+  });\n \n   return result;\n }" },
      { kind: "heading", text: "src/coupon/redemption-key.ts" },
      { kind: "code", text: "+ export function createRedemptionKey(\n+   transactionId: string,\n+   couponInstanceId: string,\n+ ) {\n+   return `${transactionId}:${couponInstanceId}`;\n+ }\n+\n+ export function reuseOriginalKey(record: RedemptionRecord) {\n+   return record.idempotencyKey;\n+ }" },
      { kind: "heading", text: "尚未覆盖的路径" },
      { kind: "code", text: "// TODO(business-decision)\n// refund: should partial refund reuse the original key?\n// cancellation: restore coupon after payment rollback?\n// manual recovery: which states may operators reset?\n\nthrow new BusinessRulePendingError('coupon recovery boundary');" },
    ],
  },
};

function ResourceDocumentViewer({ document, title }: { document: ResourceDocument; title: string }) {
  return (
    <div className={`resource-document-canvas ${document.format}`}>
      <article className="resource-document-paper">
        <header><small>{document.eyebrow}</small><h1>{title}</h1></header>
        {document.blocks.map((block, index) => {
          if (block.kind === "heading") return <h2 key={index}>{block.text}</h2>;
          if (block.kind === "paragraph") return <p key={index}>{block.text}</p>;
          if (block.kind === "callout") return <aside className="resource-document-callout" key={index}><small>{block.label}</small><p>{block.text}</p></aside>;
          if (block.kind === "list") return <ul key={index}>{block.items.map((item) => <li key={item}>{item}</li>)}</ul>;
          if (block.kind === "code") return <pre key={index}><code>{block.text}</code></pre>;
          return <div className="resource-document-table-wrap" key={index}><table><tbody>{block.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell) => rowIndex === 0 ? <th key={cell}>{cell}</th> : <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>;
        })}
      </article>
    </div>
  );
}

export function ResourceLibrary({ selectedId, sources }: { selectedId: string; sources: EnterpriseSource[] }) {
  const selectedSource = sources.find((source) => source.id === selectedId);
  const selectedDocument = selectedSource ? resourceDocuments[selectedSource.id] : undefined;

  if (selectedSource && selectedDocument) {
    return <section className="resource-detail-view">
      <header className="resource-detail-toolbar">
        <div><FileText size={16} /><span><strong>{selectedSource.title}</strong><small>{selectedDocument.updated}</small></span></div>
        <span className="resource-detail-permission"><ShieldCheck size={13} />可读取</span>
        <span className="resource-detail-page">{selectedDocument.format.toUpperCase()} · {selectedDocument.page}</span>
      </header>
      <ResourceDocumentViewer document={selectedDocument} title={selectedSource.title} />
    </section>;
  }

  return <section className="resource-library-empty"><strong>文件不可用</strong><span>请从左侧选择其他文件。</span></section>;
}
